apiVersion: apps/v1
kind: Deployment
metadata:
  name: dig-deployment
  namespace: dev
  labels:
    deployment: dig
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: dig
  template:
    metadata:
      labels:
        pod: dig
    spec:
      containers:
      - name: dig
        image:  tutum/dnsutils
        args: [bash, -c, "while true; do echo '---'; dig +short +search whoami; sleep 10; done;"]
        ports:
        - containerPort: 80
