apiVersion: batch/v1
kind: Job
metadata:
  name: dnsutils
spec:
  template:
    spec:
      containers:
      - name: dnsutils
        image:  tutum/dnsutils
        command: 
          - bash
          - -c
          - "dig +short +search whoami && sleep 1200"
      restartPolicy: Never
  backoffLimit: 4