apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: dev
  labels:
    service: whoami
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 80
  selector:
    deployment: whoami
